import{S as d,i as l}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();async function p(s){throw new Error("Pixabay API key is missing. Please add it to your .env file")}const u=document.querySelector(".gallery"),c=document.querySelector(".loader");u||console.error('Gallery element not found! Make sure you have element with class "gallery"');c||console.error('Loader element not found! Make sure you have element with class "loader"');const y=new d(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){if(!Array.isArray(s)||s.length===0){console.warn("No images to display");return}const o=s.map(({webformatURL:i,largeImageURL:r,tags:e,likes:t,views:a,comments:f,downloads:m})=>`
      <li class="gallery-item">
        <a href="${r}">
          <img src="${i}" alt="${e}" class="gallery-image" loading="lazy">
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${t}</p>
          <p class="info-item"><b>Views:</b> ${a}</p>
          <p class="info-item"><b>Comments:</b> ${f}</p>
          <p class="info-item"><b>Downloads:</b> ${m}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",o),y.refresh()}function g(){u&&(u.innerHTML="")}function b(){c&&c.classList.remove("is-hidden")}function w(){c&&c.classList.add("is-hidden")}const n=document.querySelector(".form");n||console.error('Form element not found! Make sure you have form with class "form"');l.settings({timeout:5e3,resetOnHover:!0,icon:"material-icons",transitionIn:"flipInX",transitionOut:"flipOutX"});n==null||n.addEventListener("submit",async s=>{s.preventDefault();const o=n.elements["search-text"];if(!o){console.error('Search input not found! Make sure input has name="search-text"');return}const i=o.value.trim();if(!i){l.warning({title:"Warning",message:"Search input must not be empty!",position:"topRight"});return}g(),b();try{const r=await p(i);r.hits.length===0?l.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(h(r.hits),l.success({title:"Success",message:`Found ${r.totalHits} images`,position:"topRight"}))}catch(r){console.error("Search error:",r),l.error({title:"Error",message:`Something went wrong: ${r.message}`,position:"topRight"})}finally{w(),n.reset()}});
//# sourceMappingURL=index.js.map
